pid = /tmp/stunnel.pid
foreground = yes

[redis]
client = yes
accept = 127.0.0.1:6379        # porta local para a aplicação
connect = redis-10473.c84.us-east-1-2.ec2.redns.redis-cloud.com:10473  # host + porta SSL
verify = 0                     # ignora validação de certificado (somente teste)